package io.ipbreaker.wallet.rights.event;

public enum DomainEventType {
    IP_ASSET_REGISTERED,
    IP_ASSET_TRANSFERRED,
    EVIDENCE_ADDED,
    EVIDENCE_STATUS_CHANGED,
    LICENSE_OFFER_CREATED,
    LICENSE_OFFER_STATUS_UPDATED,
    LICENSE_PURCHASED,
    LICENSE_CERTIFICATE_TRANSFERRED,
    LICENSE_AGREEMENT_CREATED,
    LICENSE_STATUS_CHANGED,
    LICENSE_FUNDED,
    LICENSE_PERFORMANCE_CONFIRMED,
    LICENSE_FUNDS_RELEASED,
    LICENSE_DISPUTE_RAISED,
    LICENSE_DISPUTE_RESOLVED,
    LICENSE_AGREEMENT_CANCELLED,
    LICENSE_GLOBAL_ARBITER_UPDATED,
    KNOWN_INFRASTRUCTURE_EVENT,
    UNKNOWN_CONTRACT_EVENT
}
