package io.ipbreaker.wallet.application.settlement;

public enum EligibilityReasonCode {
    ASSET_NOT_FOUND,
    ASSET_NOT_ACTIVE,
    LICENSOR_NOT_CURRENT_OWNER,
    TERMS_HASH_MISMATCH,
    AGREEMENT_NOT_SETTLEABLE,
    ASSET_ID_MISMATCH,
    PAYER_NOT_LICENSEE,
    PAYEE_NOT_LICENSOR,
    AMOUNT_MISMATCH,
    CURRENCY_UNSUPPORTED,
    PAYMENT_NOT_OBSERVED,
    PAYMENT_PAYER_MISMATCH,
    PAYMENT_AMOUNT_MISMATCH
}
