<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>io.patex.wallet</groupId><artifactId>patex-wallet-service</artifactId><version>0.1.0-SNAPSHOT</version></parent><artifactId>patex-wallet-job</artifactId><dependencies><dependency><groupId>io.patex.wallet</groupId><artifactId>patex-wallet-application</artifactId><version>${project.version}</version></dependency><dependency><groupId>io.patex.wallet</groupId><artifactId>patex-wallet-chain</artifactId><version>${project.version}</version></dependency></dependencies></project>

